# Generated by Django 4.2.4 on 2023-08-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.todo')),
            ],
        ),
    ]
