# Generated by Django 4.2.4 on 2023-08-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_todo_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='items',
        ),
        migrations.AlterField(
            model_name='item',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='app.todo'),
        ),
    ]
